// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSArxE1Bjz9vukqJjHiskjLPy2V7JFKBk',
    appId: '1:271915370172:web:df741af6c3f7043ba872b9',
    messagingSenderId: '271915370172',
    projectId: 'onlyplants-3b597',
    authDomain: 'onlyplants-3b597.firebaseapp.com',
    storageBucket: 'onlyplants-3b597.appspot.com',
    measurementId: 'G-YF9L3PS6HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd1JGCPw10LHAnESXCJMxwnGmDsdxA3f0',
    appId: '1:271915370172:android:83e06d18db765a56a872b9',
    messagingSenderId: '271915370172',
    projectId: 'onlyplants-3b597',
    storageBucket: 'onlyplants-3b597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQLSK8sX8xlV5tU05VVKVUCEjvanxvRUY',
    appId: '1:271915370172:ios:4462496ef4b58aa5a872b9',
    messagingSenderId: '271915370172',
    projectId: 'onlyplants-3b597',
    storageBucket: 'onlyplants-3b597.appspot.com',
    iosBundleId: 'com.example.onlyPlants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQLSK8sX8xlV5tU05VVKVUCEjvanxvRUY',
    appId: '1:271915370172:ios:5abb22988ca272b2a872b9',
    messagingSenderId: '271915370172',
    projectId: 'onlyplants-3b597',
    storageBucket: 'onlyplants-3b597.appspot.com',
    iosBundleId: 'com.example.onlyPlants.RunnerTests',
  );
}
